name: "🚀 Publish"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
  release:
    name: 🚀 Publsih
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.1.1
      - name: 🟢 node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: 🚀 publish
        run: npm publish
        working-directory: my-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
